# Generated by Django 2.1.2 on 2018-11-11 15:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincoln_app', '0002_publicart2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('objectid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('bldg_name', models.CharField(blank=True, max_length=128, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='POINT(<django.db.models.fields.FloatField> <django.db.models.fields.FloatField>)')),
            ],
            options={
                'db_table': 'zoo',
                'managed': False,
            },
        ),
    ]
