# Generated by Django 2.1.2 on 2018-11-11 22:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincoln_app', '0003_zoo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('geoid', models.SmallIntegerField(blank=True, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(blank=True, max_length=128, null=True)),
                ('concession', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'restaurants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('geoid', models.SmallIntegerField(blank=True, primary_key=True, serialize=False)),
                ('facility', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'sports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterLeisure',
            fields=[
                ('geoid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(blank=True, max_length=128)),
                ('place', models.CharField(blank=True, max_length=128, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'water_leisure',
                'managed': False,
            },
        ),
    ]
