# Generated by Django 2.1.2 on 2018-11-17 06:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincoln_app', '0004_restaurants_sports_waterleisure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllLayers',
            fields=[
                ('geoid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(blank=True, max_length=128, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=128, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'all_layers',
                'managed': False,
            },
        ),
    ]
